### ISSUE TITLE
Collections not auto populating 

### ISSUE THREAD

**Issue by VCSJacob** [firecmsco/firecms#656]
In FireCMS cloud and on localhost my collections are not auto-updating when a new one is created in Firestore. I define my own collection ID in my client react app and send over an array of data then, it creates a subcollection. Nothing is updated in FireCMS at this time. 
When I manually add the define the collection in FireCMS using the button in the top right corner and enter the ID shown in Firestore created by my react app, all the correct data is shown in the subcollection. 
Why doesn't it auto-update collection views? This almost makes it unusable as a CMS for this reason. I can't expect my team to define every collection name when they need access to that data.

**Comment by fgatti675** [comment]
Hi @VCSJacob 
So the CMS defines a schema for each collection where each property has a specific data type. That is not the case for Firebase, which is schemaless. The CMS is in a different conceptual layer as the database, and behaves like an independent app. For your use case it may make sense to have every collection mapped, but for other people it isn't (this had not been requested before). Many people just want to map some collections, and many have different mapping based on the logged in user. This is not something we can do automatically.
We offer the functionality to infer collection schemas with one click, but we can't be 100% that the schema is correct, so users are ultimately responsible for picking the right schemas.
Maybe you are looking more for a database admin, instead of a CMS?

> Why doesn't it auto-update collection views? This almost makes it unusable as a CMS for this reason. I can't expect my
> team to define every collection name when they need access to that data.

You should be able to update new properties with one tap
